name: Update common issues

on:
  schedule:
    - cron: "0 11 * * *"  # 7am eastern time
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets._GITHUB_API_KEY }}

jobs:
  UpdateCommonIssues:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        run: git clone https://x-access-token:${{ secrets._GITHUB_API_KEY }}@github.com/bids-dandisets/dashboard.git

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13
      - name: Install dependencies
        run: pip install dandi tabulate2 tqdm

      - name: Run dashboard update
        run: python dashboard/scripts/update_common_issues.py

      - name: Upload changes
        run: |
          cd dashboard
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit --message "update" || true  # || true in case of no changes
          git push

  NotifyOnFailure:
    runs-on: ubuntu-latest
    needs: [ UpdateCommonIssues ]
    if: ${{ always() && needs.UpdateCommonIssues.result == 'failure' }}
    steps:
      - uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "CI Failure: BIDS-Dandisets Common Issues Update"
          to: cody.c.baker.phd@gmail.com  # Add more with comma separation (no spaces)
          from: bids-dandisets
          body: "Please check the latest run of the BIDS-Dandisets Common Issues update: https://github.com/bids-dandisets/dashboard/actions/workflows/update-common-issues.yml"
